# Generated by Django 2.2.2 on 2019-06-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='誕生日'),
        ),
    ]
