# Generated by Django 2.2.2 on 2019-06-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='brokerage_fee',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='仲介手数料'),
        ),
    ]
