# Generated by Django 2.2.2 on 2019-06-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_data', '0002_auto_20190624_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='ad_payment_amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='AD入金額'),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='bf_payment_amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='仲手入金額'),
        ),
    ]
