# Generated by Django 2.2.2 on 2019-07-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20190702_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, verbose_name='目的'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='詳細'),
        ),
    ]
