# Generated by Django 2.2.2 on 2019-07-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20190702_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='user_id',
            field=models.CharField(max_length=50, verbose_name='ユーザーID'),
        ),
    ]
