# Generated by Django 2.2.2 on 2019-07-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20190702_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='user_id',
            field=models.IntegerField(verbose_name='ユーザーID'),
        ),
    ]
